//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMINBASCKET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITEMINBASCKET()
        {
            this.ITEMORDER = new HashSet<ITEMORDER>();
        }
    
        public decimal ITEMINBASCKETID { get; set; }
        public decimal BASCKETID { get; set; }
        public decimal ITEMID { get; set; }
    
        public virtual BASCKET BASCKET { get; set; }
        public virtual ITEMS ITEMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEMORDER> ITEMORDER { get; set; }
    }
}
