//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMORDER
    {
        public decimal ORDERID { get; set; }
        public decimal ITEMINBASCKETID { get; set; }
        public decimal ITEMORDERID { get; set; }
    
        public virtual ITEMINBASCKET ITEMINBASCKET { get; set; }
        public virtual ORDERS ORDERS { get; set; }
    }
}
