//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITEMS()
        {
            this.ITEMINBASCKET = new HashSet<ITEMINBASCKET>();
        }
    
        public decimal ITEMID { get; set; }
        public string ITEMNAME { get; set; }
        public decimal PRISELISTID { get; set; }
        public decimal SUPPLIERID { get; set; }
        public decimal CATEGORYID { get; set; }
    
        public virtual CATEGORIES CATEGORIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEMINBASCKET> ITEMINBASCKET { get; set; }
        public virtual PRISELIST PRISELIST { get; set; }
        public virtual SUPPLIERS SUPPLIERS { get; set; }
    }
}
