//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_APPLICATIONFILES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MD_APPLICATIONFILES()
        {
            this.MD_FILE_ARTIFACTS = new HashSet<MD_FILE_ARTIFACTS>();
        }
    
        public decimal ID { get; set; }
        public decimal APPLICATIONS_ID_FK { get; set; }
        public string NAME { get; set; }
        public string URI { get; set; }
        public string TYPE { get; set; }
        public string STATE { get; set; }
        public string LANGUAGE { get; set; }
        public Nullable<decimal> LOC { get; set; }
        public decimal SECURITY_GROUP_ID { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_ON { get; set; }
        public string UPDATED_BY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MD_FILE_ARTIFACTS> MD_FILE_ARTIFACTS { get; set; }
        public virtual MD_APPLICATIONS MD_APPLICATIONS { get; set; }
    }
}
