//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_COLUMNS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MD_COLUMNS()
        {
            this.MD_CONSTRAINT_DETAILS = new HashSet<MD_CONSTRAINT_DETAILS>();
            this.MD_INDEX_DETAILS = new HashSet<MD_INDEX_DETAILS>();
        }
    
        public decimal ID { get; set; }
        public decimal TABLE_ID_FK { get; set; }
        public string COLUMN_NAME { get; set; }
        public decimal COLUMN_ORDER { get; set; }
        public string COLUMN_TYPE { get; set; }
        public Nullable<decimal> PRECISION { get; set; }
        public Nullable<decimal> SCALE { get; set; }
        public string NULLABLE { get; set; }
        public string DEFAULT_VALUE { get; set; }
        public string NATIVE_SQL { get; set; }
        public string NATIVE_KEY { get; set; }
        public string DATATYPE_TRANSFORMED_FLAG { get; set; }
        public string COMMENTS { get; set; }
        public decimal SECURITY_GROUP_ID { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_ON { get; set; }
    
        public virtual MD_TABLES MD_TABLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MD_CONSTRAINT_DETAILS> MD_CONSTRAINT_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MD_INDEX_DETAILS> MD_INDEX_DETAILS { get; set; }
    }
}
