//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_DERIVATIVES
    {
        public decimal ID { get; set; }
        public decimal SRC_ID { get; set; }
        public string SRC_TYPE { get; set; }
        public decimal DERIVED_ID { get; set; }
        public string DERIVED_TYPE { get; set; }
        public decimal DERIVED_CONNECTION_ID_FK { get; set; }
        public string TRANSFORMED { get; set; }
        public string ORIGINAL_IDENTIFIER { get; set; }
        public string NEW_IDENTIFIER { get; set; }
        public string DERIVED_OBJECT_NAMESPACE { get; set; }
        public string DERIVATIVE_REASON { get; set; }
        public decimal SECURITY_GROUP_ID { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_ON { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public string ENABLED { get; set; }
    
        public virtual MD_CONNECTIONS MD_CONNECTIONS { get; set; }
    }
}
