//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_PRIVILEGES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MD_PRIVILEGES()
        {
            this.MD_GROUP_PRIVILEGES = new HashSet<MD_GROUP_PRIVILEGES>();
            this.MD_USER_PRIVILEGES = new HashSet<MD_USER_PRIVILEGES>();
        }
    
        public decimal ID { get; set; }
        public decimal SCHEMA_ID_FK { get; set; }
        public string PRIVILEGE_NAME { get; set; }
        public Nullable<decimal> PRIVELEGE_OBJECT_ID { get; set; }
        public string PRIVELEGEOBJECTTYPE { get; set; }
        public string PRIVELEGE_TYPE { get; set; }
        public string ADMIN_OPTION { get; set; }
        public string NATIVE_SQL { get; set; }
        public string NATIVE_KEY { get; set; }
        public string COMMENTS { get; set; }
        public decimal SECURITY_GROUP_ID { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_ON { get; set; }
        public string LAST_UPDATED_BY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MD_GROUP_PRIVILEGES> MD_GROUP_PRIVILEGES { get; set; }
        public virtual MD_SCHEMAS MD_SCHEMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MD_USER_PRIVILEGES> MD_USER_PRIVILEGES { get; set; }
    }
}
