//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_STORED_PROGRAMS
    {
        public decimal ID { get; set; }
        public decimal SCHEMA_ID_FK { get; set; }
        public string PROGRAMTYPE { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> PACKAGE_ID_FK { get; set; }
        public string NATIVE_SQL { get; set; }
        public string NATIVE_KEY { get; set; }
        public string LANGUAGE { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<decimal> LINECOUNT { get; set; }
        public decimal SECURITY_GROUP_ID { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_ON { get; set; }
        public string LAST_UPDATED_BY { get; set; }
    
        public virtual MD_PACKAGES MD_PACKAGES { get; set; }
        public virtual MD_SCHEMAS MD_SCHEMAS { get; set; }
    }
}
