//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIGR_GENERATION_ORDER
    {
        public decimal ID { get; set; }
        public decimal CONNECTION_ID_FK { get; set; }
        public decimal OBJECT_ID { get; set; }
        public string OBJECT_TYPE { get; set; }
        public decimal GENERATION_ORDER { get; set; }
    
        public virtual MD_CONNECTIONS MD_CONNECTIONS { get; set; }
    }
}
