//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDERS()
        {
            this.ITEMORDER = new HashSet<ITEMORDER>();
        }
    
        public decimal ORDERID { get; set; }
        public decimal BASCKETID { get; set; }
        public decimal STOCKID { get; set; }
        public decimal MANEGERID { get; set; }
        public System.DateTime ORDERDATA { get; set; }
        public System.DateTime ARRIVEDATA { get; set; }
        public string INVOICENUMBER { get; set; }
        public decimal SUMM { get; set; }
    
        public virtual BASCKET BASCKET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEMORDER> ITEMORDER { get; set; }
        public virtual MANAGERS MANAGERS { get; set; }
        public virtual STOCK STOCK { get; set; }
    }
}
