//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BASCKET> BASCKET { get; set; }
        public virtual DbSet<CATEGORIES> CATEGORIES { get; set; }
        public virtual DbSet<GROUPS> GROUPS { get; set; }
        public virtual DbSet<GUEST> GUEST { get; set; }
        public virtual DbSet<ITEMINBASCKET> ITEMINBASCKET { get; set; }
        public virtual DbSet<ITEMORDER> ITEMORDER { get; set; }
        public virtual DbSet<ITEMS> ITEMS { get; set; }
        public virtual DbSet<MANAGERS> MANAGERS { get; set; }
        public virtual DbSet<MD_ADDITIONAL_PROPERTIES> MD_ADDITIONAL_PROPERTIES { get; set; }
        public virtual DbSet<MD_APPLICATIONFILES> MD_APPLICATIONFILES { get; set; }
        public virtual DbSet<MD_APPLICATIONS> MD_APPLICATIONS { get; set; }
        public virtual DbSet<MD_CATALOGS> MD_CATALOGS { get; set; }
        public virtual DbSet<MD_COLUMNS> MD_COLUMNS { get; set; }
        public virtual DbSet<MD_CONNECTIONS> MD_CONNECTIONS { get; set; }
        public virtual DbSet<MD_CONSTRAINT_DETAILS> MD_CONSTRAINT_DETAILS { get; set; }
        public virtual DbSet<MD_CONSTRAINTS> MD_CONSTRAINTS { get; set; }
        public virtual DbSet<MD_DERIVATIVES> MD_DERIVATIVES { get; set; }
        public virtual DbSet<MD_FILE_ARTIFACTS> MD_FILE_ARTIFACTS { get; set; }
        public virtual DbSet<MD_GROUP_MEMBERS> MD_GROUP_MEMBERS { get; set; }
        public virtual DbSet<MD_GROUP_PRIVILEGES> MD_GROUP_PRIVILEGES { get; set; }
        public virtual DbSet<MD_GROUPS> MD_GROUPS { get; set; }
        public virtual DbSet<MD_INDEX_DETAILS> MD_INDEX_DETAILS { get; set; }
        public virtual DbSet<MD_INDEXES> MD_INDEXES { get; set; }
        public virtual DbSet<MD_MIGR_DEPENDENCY> MD_MIGR_DEPENDENCY { get; set; }
        public virtual DbSet<MD_MIGR_PARAMETER> MD_MIGR_PARAMETER { get; set; }
        public virtual DbSet<MD_MIGR_WEAKDEP> MD_MIGR_WEAKDEP { get; set; }
        public virtual DbSet<MD_OTHER_OBJECTS> MD_OTHER_OBJECTS { get; set; }
        public virtual DbSet<MD_PACKAGES> MD_PACKAGES { get; set; }
        public virtual DbSet<MD_PARTITIONS> MD_PARTITIONS { get; set; }
        public virtual DbSet<MD_PRIVILEGES> MD_PRIVILEGES { get; set; }
        public virtual DbSet<MD_PROJECTS> MD_PROJECTS { get; set; }
        public virtual DbSet<MD_REGISTRY> MD_REGISTRY { get; set; }
        public virtual DbSet<MD_SCHEMAS> MD_SCHEMAS { get; set; }
        public virtual DbSet<MD_SEQUENCES> MD_SEQUENCES { get; set; }
        public virtual DbSet<MD_STORED_PROGRAMS> MD_STORED_PROGRAMS { get; set; }
        public virtual DbSet<MD_SYNONYMS> MD_SYNONYMS { get; set; }
        public virtual DbSet<MD_TABLES> MD_TABLES { get; set; }
        public virtual DbSet<MD_TABLESPACES> MD_TABLESPACES { get; set; }
        public virtual DbSet<MD_TRIGGERS> MD_TRIGGERS { get; set; }
        public virtual DbSet<MD_USER_DEFINED_DATA_TYPES> MD_USER_DEFINED_DATA_TYPES { get; set; }
        public virtual DbSet<MD_USER_PRIVILEGES> MD_USER_PRIVILEGES { get; set; }
        public virtual DbSet<MD_USERS> MD_USERS { get; set; }
        public virtual DbSet<MD_VIEWS> MD_VIEWS { get; set; }
        public virtual DbSet<MIGR_DATATYPE_TRANSFORM_MAP> MIGR_DATATYPE_TRANSFORM_MAP { get; set; }
        public virtual DbSet<MIGR_DATATYPE_TRANSFORM_RULE> MIGR_DATATYPE_TRANSFORM_RULE { get; set; }
        public virtual DbSet<MIGR_GENERATION_ORDER> MIGR_GENERATION_ORDER { get; set; }
        public virtual DbSet<MIGRLOG> MIGRLOG { get; set; }
        public virtual DbSet<ORDERS> ORDERS { get; set; }
        public virtual DbSet<PRISELIST> PRISELIST { get; set; }
        public virtual DbSet<STAGE_MIGRLOG> STAGE_MIGRLOG { get; set; }
        public virtual DbSet<STOCK> STOCK { get; set; }
        public virtual DbSet<STUDENT> STUDENT { get; set; }
        public virtual DbSet<SUPPLIERS> SUPPLIERS { get; set; }
        public virtual DbSet<USERINF> USERINF { get; set; }
        public virtual DbSet<USERSS> USERSS { get; set; }
        public virtual DbSet<LOG> LOG { get; set; }
        public virtual DbSet<MD_CODE_REGEX> MD_CODE_REGEX { get; set; }
        public virtual DbSet<MD_REPOVERSIONS> MD_REPOVERSIONS { get; set; }
        public virtual DbSet<MIGRATION_RESERVED_WORDS> MIGRATION_RESERVED_WORDS { get; set; }
        public virtual DbSet<SS2K5_CHECK_CONSTRAINTS> SS2K5_CHECK_CONSTRAINTS { get; set; }
        public virtual DbSet<SS2K5_COLUMNS> SS2K5_COLUMNS { get; set; }
        public virtual DbSet<SS2K5_DATABASE_PRINCIPALS> SS2K5_DATABASE_PRINCIPALS { get; set; }
        public virtual DbSet<SS2K5_DATABASE_ROLE_MEMBERS> SS2K5_DATABASE_ROLE_MEMBERS { get; set; }
        public virtual DbSet<SS2K5_DATABASES> SS2K5_DATABASES { get; set; }
        public virtual DbSet<SS2K5_DEFAULT_CONSTRAINTS> SS2K5_DEFAULT_CONSTRAINTS { get; set; }
        public virtual DbSet<SS2K5_FOREIGN_KEY_COLUMNS> SS2K5_FOREIGN_KEY_COLUMNS { get; set; }
        public virtual DbSet<SS2K5_FOREIGN_KEYS> SS2K5_FOREIGN_KEYS { get; set; }
        public virtual DbSet<SS2K5_IDENTITY_COLUMNS> SS2K5_IDENTITY_COLUMNS { get; set; }
        public virtual DbSet<SS2K5_INDEX_COLUMNS> SS2K5_INDEX_COLUMNS { get; set; }
        public virtual DbSet<SS2K5_INDEXES> SS2K5_INDEXES { get; set; }
        public virtual DbSet<SS2K5_OBJECTS> SS2K5_OBJECTS { get; set; }
        public virtual DbSet<SS2K5_SCHEMAS> SS2K5_SCHEMAS { get; set; }
        public virtual DbSet<SS2K5_SCHEMATA> SS2K5_SCHEMATA { get; set; }
        public virtual DbSet<SS2K5_SERVER_PRINCIPALS> SS2K5_SERVER_PRINCIPALS { get; set; }
        public virtual DbSet<SS2K5_SQL_MODULES> SS2K5_SQL_MODULES { get; set; }
        public virtual DbSet<SS2K5_SYSPROPERTIES> SS2K5_SYSPROPERTIES { get; set; }
        public virtual DbSet<SS2K5_TABLE_PRIVILEGES> SS2K5_TABLE_PRIVILEGES { get; set; }
        public virtual DbSet<SS2K5_TABLES> SS2K5_TABLES { get; set; }
        public virtual DbSet<SS2K5_TYPES> SS2K5_TYPES { get; set; }
        public virtual DbSet<STAGE_SS2K5_CHECK_CONSTRAINTS> STAGE_SS2K5_CHECK_CONSTRAINTS { get; set; }
        public virtual DbSet<STAGE_SS2K5_COLUMNS> STAGE_SS2K5_COLUMNS { get; set; }
        public virtual DbSet<STAGE_SS2K5_DATABASES> STAGE_SS2K5_DATABASES { get; set; }
        public virtual DbSet<STAGE_SS2K5_DB_PRINCIPALS> STAGE_SS2K5_DB_PRINCIPALS { get; set; }
        public virtual DbSet<STAGE_SS2K5_DB_ROLE_MEMBERS> STAGE_SS2K5_DB_ROLE_MEMBERS { get; set; }
        public virtual DbSet<STAGE_SS2K5_DT_CONSTRAINTS> STAGE_SS2K5_DT_CONSTRAINTS { get; set; }
        public virtual DbSet<STAGE_SS2K5_FN_KEY_COLUMNS> STAGE_SS2K5_FN_KEY_COLUMNS { get; set; }
        public virtual DbSet<STAGE_SS2K5_FN_KEYS> STAGE_SS2K5_FN_KEYS { get; set; }
        public virtual DbSet<STAGE_SS2K5_IDENTITY_COLUMNS> STAGE_SS2K5_IDENTITY_COLUMNS { get; set; }
        public virtual DbSet<STAGE_SS2K5_INDEX_COLUMNS> STAGE_SS2K5_INDEX_COLUMNS { get; set; }
        public virtual DbSet<STAGE_SS2K5_INDEXES> STAGE_SS2K5_INDEXES { get; set; }
        public virtual DbSet<STAGE_SS2K5_OBJECTS> STAGE_SS2K5_OBJECTS { get; set; }
        public virtual DbSet<STAGE_SS2K5_SCHEMAS> STAGE_SS2K5_SCHEMAS { get; set; }
        public virtual DbSet<STAGE_SS2K5_SCHEMATA> STAGE_SS2K5_SCHEMATA { get; set; }
        public virtual DbSet<STAGE_SS2K5_SERVER_PRINCIPALS> STAGE_SS2K5_SERVER_PRINCIPALS { get; set; }
        public virtual DbSet<STAGE_SS2K5_SQL_MODULES> STAGE_SS2K5_SQL_MODULES { get; set; }
        public virtual DbSet<STAGE_SS2K5_SYSPROPERTIES> STAGE_SS2K5_SYSPROPERTIES { get; set; }
        public virtual DbSet<STAGE_SS2K5_TABLE_PRIVILEGES> STAGE_SS2K5_TABLE_PRIVILEGES { get; set; }
        public virtual DbSet<STAGE_SS2K5_TABLES> STAGE_SS2K5_TABLES { get; set; }
        public virtual DbSet<STAGE_SS2K5_TYPES> STAGE_SS2K5_TYPES { get; set; }
        public virtual DbSet<STAGE_SYB12_SYSINDEXES> STAGE_SYB12_SYSINDEXES { get; set; }
        public virtual DbSet<STAGE_SYB12_SYSOBJECTS> STAGE_SYB12_SYSOBJECTS { get; set; }
        public virtual DbSet<STAGE_SYB12_SYSUSERS> STAGE_SYB12_SYSUSERS { get; set; }
        public virtual DbSet<SYB12_SYSCONSTRAINTS> SYB12_SYSCONSTRAINTS { get; set; }
        public virtual DbSet<SYB12_SYSINDEXES> SYB12_SYSINDEXES { get; set; }
        public virtual DbSet<SYB12_SYSOBJECTS> SYB12_SYSOBJECTS { get; set; }
        public virtual DbSet<SYB12_SYSUSERS> SYB12_SYSUSERS { get; set; }
    }
}
