//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS2K5_DATABASE_PRINCIPALS
    {
        public Nullable<int> DB_ID { get; set; }
        public string DEFAULT_SCHEMA_NAME { get; set; }
        public string TYPE { get; set; }
        public int PRINCIPAL_ID { get; set; }
        public Nullable<int> OWNING_PRINCIPAL_ID { get; set; }
        public string NAME { get; set; }
        public byte[] SID { get; set; }
    }
}
