//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS2K5_FOREIGN_KEY_COLUMNS
    {
        public Nullable<int> DB_ID { get; set; }
        public int CONSTRAINT_COLUMN_ID { get; set; }
        public int CONSTRAINT_OBJECT_ID { get; set; }
        public int PARENT_OBJECT_ID { get; set; }
        public int PARENT_COLUMN_ID { get; set; }
        public int REFERENCED_COLUMN_ID { get; set; }
        public int REFERENCED_OBJECT_ID { get; set; }
    }
}
