//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS2K5_COLUMNS
    {
        public Nullable<int> DB_ID { get; set; }
        public string NAME { get; set; }
        public int RULE_OBJECT_ID { get; set; }
        public int COLUMN_ID { get; set; }
        public short MAX_LENGTH { get; set; }
        public short PRECISION { get; set; }
        public short SCALE { get; set; }
        public Nullable<short> IS_NULLABLE { get; set; }
        public int USER_TYPE_ID { get; set; }
        public short SYSTEM_TYPE_ID { get; set; }
        public int DEFAULT_OBJECT_ID { get; set; }
        public int OBJECT_ID { get; set; }
    }
}
