//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS2K5_SYSPROPERTIES
    {
        public Nullable<short> DB_ID { get; set; }
        public short MAJOR_ID { get; set; }
        public short MINOR_ID { get; set; }
        public string NAME { get; set; }
        public string VALUE { get; set; }
    }
}
