//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS2K5_IDENTITY_COLUMNS
    {
        public Nullable<decimal> DB_ID { get; set; }
        public Nullable<decimal> SEED_VALUE { get; set; }
        public Nullable<decimal> INCREMENT_VALUE { get; set; }
        public Nullable<decimal> LAST_VALUE { get; set; }
        public decimal OBJECT_ID { get; set; }
        public decimal COLUMN_ID { get; set; }
    }
}
