//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAGE_SS2K5_FN_KEY_COLUMNS
    {
        public Nullable<decimal> SVRID_FK { get; set; }
        public Nullable<decimal> DBID_GEN_FK { get; set; }
        public decimal CONSTRAINT_COLUMN_ID { get; set; }
        public decimal CONSTRAINT_OBJECT_ID { get; set; }
        public decimal PARENT_OBJECT_ID { get; set; }
        public decimal PARENT_COLUMN_ID { get; set; }
        public decimal REFERENCED_COLUMN_ID { get; set; }
        public decimal REFERENCED_OBJECT_ID { get; set; }
    }
}
