//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAGE_SS2K5_COLUMNS
    {
        public Nullable<decimal> SVRID_FK { get; set; }
        public Nullable<decimal> DBID_GEN_FK { get; set; }
        public Nullable<decimal> ID_GEN_FK { get; set; }
        public Nullable<decimal> COLID_GEN { get; set; }
        public string NAME { get; set; }
        public decimal RULE_OBJECT_ID { get; set; }
        public decimal COLUMN_ID { get; set; }
        public short MAX_LENGTH { get; set; }
        public short PRECISION { get; set; }
        public short SCALE { get; set; }
        public Nullable<short> IS_NULLABLE { get; set; }
        public decimal USER_TYPE_ID { get; set; }
        public short SYSTEM_TYPE_ID { get; set; }
        public decimal DEFAULT_OBJECT_ID { get; set; }
        public decimal OBJECT_ID { get; set; }
    }
}
