//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAGE_SS2K5_TYPES
    {
        public Nullable<decimal> SVRID_FK { get; set; }
        public Nullable<decimal> DBID_GEN_FK { get; set; }
        public string NAME { get; set; }
        public decimal USER_TYPE_ID { get; set; }
        public byte SYSTEM_TYPE_ID { get; set; }
        public Nullable<decimal> SCHEMA_ID { get; set; }
        public Nullable<decimal> MAX_LENGTH { get; set; }
        public Nullable<decimal> PRECISION { get; set; }
        public Nullable<decimal> SCALE { get; set; }
    }
}
