//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAGE_SS2K5_INDEXES
    {
        public Nullable<decimal> SVRID_FK { get; set; }
        public Nullable<decimal> DBID_GEN_FK { get; set; }
        public Nullable<decimal> OBJECT_ID_GEN { get; set; }
        public decimal OBJECT_ID { get; set; }
        public decimal INDEX_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<bool> IS_UNIQUE { get; set; }
        public Nullable<bool> IS_PRIMARY_KEY { get; set; }
    }
}
