//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAGE_SYB12_SYSUSERS
    {
        public Nullable<decimal> SVRID_FK { get; set; }
        public Nullable<decimal> DBID_GEN_FK { get; set; }
        public Nullable<decimal> SUID_GEN { get; set; }
        public Nullable<decimal> GEN_ID_FK { get; set; }
        public Nullable<decimal> SUID { get; set; }
        public decimal DB_UID { get; set; }
        public Nullable<decimal> GID { get; set; }
        public string NAME { get; set; }
        public string ENVIRON { get; set; }
    }
}
