//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAGE_SYB12_SYSOBJECTS
    {
        public Nullable<decimal> SVRID_FK { get; set; }
        public Nullable<decimal> DBID_GEN_FK { get; set; }
        public Nullable<decimal> OBJID_GEN { get; set; }
        public Nullable<decimal> SUID_GEN_FK { get; set; }
        public string NAME { get; set; }
        public decimal ID { get; set; }
        public Nullable<decimal> DB_UID { get; set; }
        public string DB_TYPE { get; set; }
        public Nullable<decimal> USERSTAT { get; set; }
        public Nullable<decimal> SYSSTAT { get; set; }
        public Nullable<decimal> INDEXDEL { get; set; }
        public Nullable<decimal> SCHEMATACNT { get; set; }
        public Nullable<decimal> SYSSTAT2 { get; set; }
        public string CRDATE { get; set; }
        public string EXPDATE { get; set; }
        public Nullable<decimal> DELTRIG { get; set; }
        public Nullable<decimal> INSTRIG { get; set; }
        public Nullable<decimal> UPDTRIG { get; set; }
        public Nullable<decimal> SELTRIG { get; set; }
        public Nullable<decimal> CKFIRST { get; set; }
        public Nullable<decimal> DB_CACHE { get; set; }
        public Nullable<decimal> AUDFLAGS { get; set; }
        public Nullable<decimal> OBJSPARE { get; set; }
        public byte[] VERSIONTS { get; set; }
        public string LOGINNAME { get; set; }
    }
}
