//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAGE_MIGRLOG
    {
        public Nullable<decimal> SVRID_FK { get; set; }
        public Nullable<decimal> DBID_GEN_FK { get; set; }
        public decimal ID { get; set; }
        public Nullable<decimal> REF_OBJECT_ID { get; set; }
        public string REF_OBJECT_TYPE { get; set; }
        public System.DateTime LOG_DATE { get; set; }
        public short SEVERITY { get; set; }
        public string LOGTEXT { get; set; }
        public string PHASE { get; set; }
    }
}
