//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        public decimal GROUP_ID { get; set; }
        public decimal ID { get; set; }
        public string NAME { get; set; }
    
        public virtual GROUPS GROUPS { get; set; }
    }
}
