//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYB12_SYSCONSTRAINTS
    {
        public Nullable<int> DB_ID { get; set; }
        public Nullable<int> TABLE_ID { get; set; }
        public string CONSTRAINT_NAME { get; set; }
        public string DB_DEFINITION { get; set; }
    }
}
