//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYB12_SYSOBJECTS
    {
        public Nullable<int> DB_ID { get; set; }
        public string NAME { get; set; }
        public int ID { get; set; }
        public Nullable<int> DB_UID { get; set; }
        public string DB_TYPE { get; set; }
        public Nullable<int> USERSTAT { get; set; }
        public Nullable<int> SYSSTAT { get; set; }
        public Nullable<int> INDEXDEL { get; set; }
        public Nullable<int> SCHEMATACNT { get; set; }
        public Nullable<int> SYSSTAT2 { get; set; }
        public string CRDATE { get; set; }
        public string EXPDATE { get; set; }
        public Nullable<int> DELTRIG { get; set; }
        public Nullable<int> INSTRIG { get; set; }
        public Nullable<int> UPDTRIG { get; set; }
        public Nullable<int> SELTRIG { get; set; }
        public Nullable<int> CKFIRST { get; set; }
        public Nullable<int> DB_CACHE { get; set; }
        public Nullable<int> AUDFLAGS { get; set; }
        public Nullable<int> OBJSPARE { get; set; }
        public byte[] VERSIONTS { get; set; }
        public string LOGINNAME { get; set; }
    }
}
