//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYB12_SYSUSERS
    {
        public Nullable<int> DB_ID { get; set; }
        public Nullable<int> SUID { get; set; }
        public int DB_UID { get; set; }
        public Nullable<int> GID { get; set; }
        public string NAME { get; set; }
        public string ENVIRON { get; set; }
    }
}
