//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERINF
    {
        public decimal USERINFID { get; set; }
        public string FULLNAME { get; set; }
        public string ADRESS { get; set; }
        public string PHONE { get; set; }
        public decimal USERID { get; set; }
    
        public virtual USERSS USERSS { get; set; }
    }
}
